//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA_Team10bCAProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueReturn
    {
        public int TransactionID { get; set; }
        public int MemberID { get; set; }
        public int BookID { get; set; }
        public System.DateTime DateIssue { get; set; }
        public System.DateTime DateExpiry { get; set; }
        public Nullable<System.DateTime> DateReturn { get; set; }
        public string LoanStatus { get; set; }
        public string Remarks { get; set; }
    
        public virtual Books Book { get; set; }
        public virtual Members Member { get; set; }
    }
}
